openapi: 3.0.0
info:
  title: My Node.js API
  version: 1.0.0
  description: A simple API for demonstration
servers:
  - url: http://localhost:3000
paths:
  /:
    get:
      summary: Root endpoint
      responses:
        '200':
          description: A successful response
  /health:
    get:
      summary: Health-check endpoint
      responses:
        '200':
          description: Service is up
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  /api/users:
    get:
      summary: Retrieve list of users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
