version: '3.8'

services:
  db:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: node_app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db:27017/mydb

